Repository Techeer-3rd-COKKIRI/backend, pull requests merged in 2022-12, with the labels that each got.

#10 [feat/#3] 예외들을 관리하고 처리하는 Handler 구현
  build.gradle
  src/main/java/com/techeer/cokkiri/global/error/ErrorCode.java
  src/main/java/com/techeer/cokkiri/global/error/ErrorResponse.java
  src/main/java/com/techeer/cokkiri/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/cokkiri/global/error/exception/BusinessException.java
  src/main/java/com/techeer/cokkiri/global/error/exception/ExampleException.java
  src/test/java/com/techeer/cokkiri/CokkiriApplicationTest.java
  src/test/java/com/techeer/cokkiri/global/error/GlobalExceptionHandlerTest.java
Labels: 기능구현

#9 [feat/#8] comment 엔티티 구현
  src/main/java/com/techeer/cokkiri/domain/comment/domain/entity/Comment.java
Labels: 기능구현

#17 [feat/#14] 회원 로그인 서비스와 로그인 기능 구현시 사용할 어노테이션 구현
  src/main/java/com/techeer/cokkiri/domain/user/controller/UserController.java
  src/main/java/com/techeer/cokkiri/domain/user/exception/UnAuthorizedAccessException.java
  src/main/java/com/techeer/cokkiri/domain/user/exception/UserNotFoundException.java
  src/main/java/com/techeer/cokkiri/domain/user/repository/UserRepository.java
  src/main/java/com/techeer/cokkiri/domain/user/service/LoginService.java
  src/main/java/com/techeer/cokkiri/domain/user/service/UserService.java
  src/main/java/com/techeer/cokkiri/global/annotation/LoginRequired.java
  src/main/java/com/techeer/cokkiri/global/annotation/LoginUser.java
  src/main/java/com/techeer/cokkiri/global/config/WebConfig.java
  src/main/java/com/techeer/cokkiri/global/error/ErrorCode.java
  src/main/java/com/techeer/cokkiri/global/interceptor/LoginInterceptor.java
  src/main/java/com/techeer/cokkiri/global/resolver/LoginUserArgumentResolver.java
  src/main/java/com/techeer/cokkiri/global/result/ResultCode.java
  src/main/java/com/techeer/cokkiri/global/result/ResultResponse.java
Labels: 기능구현

#29 [feat/#25] p6spy설정
  build.gradle
  src/main/java/com/techeer/cokkiri/domain/user/controller/UserController.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserDto.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserRegisterRequest.java
  src/main/java/com/techeer/cokkiri/global/constant/RegExp.java
Labels: 환경설정

#28 [test/#23] Study 도메인 테스트 코드 작성
  src/test/java/com/techeer/cokkiri/domain/study/controller/StudyControllerTest.java
  src/test/java/com/techeer/cokkiri/domain/study/repository/StudyRepositoryTest.java
  src/test/java/com/techeer/cokkiri/domain/study/service/StudyServiceTest.java
  src/test/java/com/techeer/cokkiri/fixture/StudyFixtures.java
  src/test/java/com/techeer/cokkiri/fixture/UserFixtures.java
Labels: 테스트

#27 [fix/#26] Study 엔티티의 접근제한자, 유효성 검증 로직 수정 및 전체적인 상태코드 수정
  .github/PULL_REQUEST_TEMPLATE.md
  src/main/java/com/techeer/cokkiri/domain/study/controller/StudyController.java
  src/main/java/com/techeer/cokkiri/domain/study/dto/StudyDto.java
  src/main/java/com/techeer/cokkiri/domain/study/service/StudyService.java
  src/main/java/com/techeer/cokkiri/global/error/ErrorCode.java
  src/main/java/com/techeer/cokkiri/global/error/GlobalExceptionHandler.java
  src/main/java/com/techeer/cokkiri/global/error/exception/ExampleException.java
  src/test/java/com/techeer/cokkiri/global/error/GlobalExceptionHandlerTest.java
Labels: 오류수정

#34 [test/#23-2] Study 도메인 테스트코드 오류 수정
  src/test/java/com/techeer/cokkiri/domain/study/controller/StudyControllerTest.java
Labels: 오류수정

#36 [fix/#35] 중복되는 DTO이름으로 인해 Swagger에서 잘못된 스키마가 노출되는 오류 수정
  src/main/java/com/techeer/cokkiri/domain/study/dto/StudyDto.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserDto.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserRegisterRequest.java
  src/main/java/com/techeer/cokkiri/global/constant/RegExp.java
Labels: 오류수정

#40 [fix/#39] BaseEntity의 isDelted에 기본값이 제대로 들어가지 않던 오류 수정
  src/main/java/com/techeer/cokkiri/global/entity/BaseEntity.java
Labels: 오류수정

#46 [chore/#45] QueryDsl 의존성 추가
  build.gradle
  src/main/java/com/techeer/cokkiri/global/config/QueryDslConfig.java
  src/test/java/com/techeer/cokkiri/fixture/UserFixtures.java
  src/test/java/com/techeer/cokkiri/global/QueryDslTest.java
Labels: 환경설정
