Repository Techeer-3rd-COKKIRI/backend, pull requests merged in 2023-01, with the labels that each got.

#41 [Feat/#38]스터디주차별로 댓글 조회 API
  src/main/java/com/techeer/cokkiri/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/cokkiri/domain/comment/dto/CommentDto.java
  src/main/java/com/techeer/cokkiri/domain/comment/mapper/CommentMapper.java
  src/main/java/com/techeer/cokkiri/domain/comment/repository/CommentRepository.java
  src/main/java/com/techeer/cokkiri/domain/comment/service/CommentService.java
  src/main/java/com/techeer/cokkiri/domain/study/dto/StudyDto.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserDto.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserRegisterRequest.java
  src/main/java/com/techeer/cokkiri/global/result/ResultCode.java
Labels: 기능구현

#48 [feat/#47] 스터디 최신순 페이징 조회 API 구현
  src/main/java/com/techeer/cokkiri/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/cokkiri/domain/comment/dto/CommentDto.java
  src/main/java/com/techeer/cokkiri/domain/study/controller/StudyController.java
  src/main/java/com/techeer/cokkiri/domain/study/dto/StudyDto.java
  src/main/java/com/techeer/cokkiri/domain/study/mapper/StudyMapper.java
  src/main/java/com/techeer/cokkiri/domain/study/repository/StudyRepository.java
  src/main/java/com/techeer/cokkiri/domain/study/service/StudyService.java
  src/main/java/com/techeer/cokkiri/global/result/ResultCode.java
Labels: 기능구현

#50 [Refactor/#49] Dto관련 수정사항 변경, Study 조회 api 수정
  src/main/java/com/techeer/cokkiri/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/cokkiri/domain/comment/dto/CommentDto.java
  src/main/java/com/techeer/cokkiri/domain/comment/mapper/CommentMapper.java
  src/main/java/com/techeer/cokkiri/domain/comment/service/CommentService.java
  src/main/java/com/techeer/cokkiri/domain/study/controller/StudyController.java
  src/main/java/com/techeer/cokkiri/domain/study/dto/StudyDto.java
  src/main/java/com/techeer/cokkiri/domain/study/mapper/StudyMapper.java
  src/main/java/com/techeer/cokkiri/domain/study/service/StudyService.java
  src/main/java/com/techeer/cokkiri/domain/user/controller/UserController.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserDto.java
  src/main/java/com/techeer/cokkiri/domain/user/dto/UserRegisterRequest.java
  src/main/java/com/techeer/cokkiri/domain/user/mapper/UserMapper.java
  src/main/java/com/techeer/cokkiri/global/constant/RegExp.java
  src/test/java/com/techeer/cokkiri/fixture/StudyFixtures.java
Labels: 리팩토링

#54 [fix/#53] 오류나는 테스트 수정, swagger에 API 제목추가, 댓글 주소 컬럼 추가
  src/main/java/com/techeer/cokkiri/domain/comment/controller/CommentController.java
  src/main/java/com/techeer/cokkiri/domain/comment/entity/Comment.java
  src/main/java/com/techeer/cokkiri/domain/study/controller/StudyController.java
  src/main/java/com/techeer/cokkiri/domain/user/controller/UserController.java
  src/test/java/com/techeer/cokkiri/global/error/GlobalExceptionHandlerTest.java
Labels: 오류수정
